

CREATE TABLE IF  NOT EXISTS model_run_instance (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
	batch_id BIGINT , 
	input_value_id BIGINT,
	output_value_id BIGINT

);

CREATE TABLE IF NOT EXISTS model_run_instance_inputs(
	model_run_instance_id BIGINT,
	input_name VARCHAR(4096),
	input_json_value VARCHAR(4096)
);

CREATE TABLE IF NOT EXISTS model_run_instance_outputs(
	model_run_instance_id BIGINT,
	output_name VARCHAR(4096),
	output_json_value VARCHAR(4096)
);





CREATE TABLE IF NOT EXISTS model_inputs(
	model_input_id BIGINT,
	name VARCHAR(4096),
	property VARCHAR(4096)
);



CREATE TABLE IF NOT EXISTS model_outputs(
	model_output_id BIGINT,
	name VARCHAR(4096),
	property VARCHAR(4096)
);

CREATE TABLE IF NOT EXISTS batch_job(
	
	id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
	model_id BIGINT,
	status VARCHAR(32)
	
);

CREATE TABLE IF NOT EXISTS models(
	id  BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
	name VARCHAR(4096),
	description VARCHAR(4096)
);

