
--EME database tabels
CREATE TABLE IF  NOT EXISTS model_run_instance(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
	batch_id BIGINT,
	time_stamp TIMESTAMP
);

CREATE TABLE IF NOT EXISTS model_run_instance_inputs(
	model_run_instance_id BIGINT,
	input_name VARCHAR(4096),
	input_json_value VARCHAR(4096)
);

CREATE TABLE IF NOT EXISTS model_run_instance_outputs(
	model_run_instance_id BIGINT,
	output_name VARCHAR(4096),
	output_json_value VARCHAR(4096)
);

CREATE TABLE IF NOT EXISTS batch_job(
	
	id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
	model_id BIGINT,
	status VARCHAR(32)
	
);


--SME database tabels
CREATE TABLE IF NOT EXISTS score_batch_job(
	
	sm_batch_job_id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
	model_id BIGINT,
	status VARCHAR(32)
	
);

CREATE TABLE IF NOT EXISTS scoring_run_instance(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
	batch_id BIGINT,
	mri_link BIGINT,
	time_stamp TIMESTAMP,
	output_json_value VARCHAR(4096)

);
CREATE TABLE IF NOT EXISTS score_model_run_instance_outputs(
	model_run_instance_id BIGINT,
	output_name VARCHAR(4096),
	output_json_value VARCHAR(4096)
);

--Work Space tabels
CREATE TABLE IF NOT EXISTS work_space(
	work_space_id GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
	batch_job_id BIGINT,
	
);
